Fix websocket examples
yesodweb/yesod pull request #1790
Opened 2022-11-13 17:29 UTC by ricky0123

Before submitting your PR, check that you've:

- [x] Bumped the version number

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

2022-11-13 17:32 UTC, ricky0123 commented
I'm still a beginner with Haskell so I don't know why this is necessary, but it should resolve #1789.

2022-11-15 17:59 UTC, snoyberg requested changes

2022-11-15 17:59 UTC, snoyberg commented on yesod-test/ChangeLog.md
> +* Fix yesod-websockets chat examples ([#1790](https://github.com/yesodweb/yesod/pull/1790)).
I think this should appear in the yesod-websockets changelog, not the yesod-test changelog.

2022-11-15 17:59 UTC, snoyberg commented on yesod-websockets/chat-with-multiple-channels.hs
> +instance Yesod App
As I understand, there was a change in Template Haskell in recent GHC versions that made this change necessary. I don't know the details, sorry.

2022-11-20 07:36 UTC, snoyberg approved these changes
Thanks!

2022-11-20 07:36 UTC, merged