Add an options data structure to allow fine-tuned control of what instances are generated for a route
yesodweb/yesod pull request #1819
Opened 2023-09-13 12:29 UTC by Benjamin-McRae-Tracsis

Before submitting your PR, check that you've:

- [x] Bumped the version number
- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddocks for new, public APIs

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

2023-09-13 13:24 UTC, parsonsmatt requested changes
So that's going to be a breaking change for any library user that uses the `Read` instance of the type

To avoid a major breaking change, we need to keep the default behavior of `deriving Read`, but provide an option for the user to disable `Read` derivation.

2023-09-13 13:33 UTC, Benjamin-McRae-Tracsis commented
I can try to work on that.

How would you want this configurable? I can make a mkRouteConsOpt that requires a config data structure, which has three booleans: `hasShow`, `hasEq`, `hasRead`, and then make duplicate versions of all the functions that call mkRouteCons that are suffixed with Opts to take said Opts.

2023-09-13 15:42 UTC, parsonsmatt commented
I'm not terribly particular. I think @snoyberg mentioned using a directive in the actual routes file would be fine - maybe something like:

```
!no-derive-read
```

as a *very* quick, patch-level fix.

Defining an `Opts` type make sense - I'd prefer a specific name (ie `RouteDeriveOpts`), and ideally a hidden constructor with setter functions so new fields aren't a breaking change. However, since we don't *need* to use this to derive instances - users can use `StandaloneDeriving` to write `deriving stock Read (Route App)`, after all - I don't anticipate many changes to this type, so hiding the constructor and setters would be a matter of taste rather than real pragmaticism.

2023-09-14 11:01 UTC, Benjamin-McRae-Tracsis commented
Are there other examples of such directives? I'm looking at the parser and I'm not sure whether it does.

2023-10-19 14:11 UTC, parsonsmatt requested changes
PR looks great, thank you! I made some suggestions for the version number + `@since` comments.

2023-10-19 14:11 UTC, parsonsmatt commented on yesod-core/yesod-core.cabal
> +version:         1.6.24.6
```suggestion
version:         1.6.25.0
```

2023-10-20 16:08 UTC, parsonsmatt approved these changes
Looks great! Thank you 😄

2023-10-23 14:39 UTC, merged

2023-10-24 11:21 UTC, snoyberg commented
@parsonsmatt absolutely, I'd be happy to. What's your Hackage username?

2023-10-24 18:14 UTC, parsonsmatt commented
It's `parsonsmatt` there too. Thank you!

2023-10-25 03:19 UTC, snoyberg commented
@parsonsmatt I've given you maintainer rights on Hackage for yesod-core and a bunch of other Yesod packages too. If you need any more, just let me know. Thank you!